[workspace]
members = [
    "chess_ui",
    "chess_core",
    "chess_mcts",
    "chess_alpha_beta",
    "chess_alpha_beta_2",
    "chess_alpha_beta_back",
    "chess_bot",
    "chess_uci",
    "chess_tournament",
    "find_magic",
]

[profile.release]
debug = true
