[build]
target = "index.html"
dist = "dist"

[[hooks]]
stage = "build"
command = "sh"
command_arguments = ["-c", "pnpx tailwindcss-cli build -i src/tailwind.css -o $TRUNK_STAGING_DIR/tailwind.css"]

[[proxy]]
rewrite = "/api/"
backend = "http://localhost:3000/api"
