[package]
name = "chess_alpha_beta_2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_core = { path = "../../core/" }
anyhow = "1.0.66"
