[package]
name = "chess_mcts"
version = "0.1.0"
authors = ["delskayn <mees.delzenne@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_core = { path = "../../core/" }
rand = "0.8.5"
anyhow = "1.0.66"
