[package]
name = "chess-uci"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { package ="chess-common", version = "0.1.0", path = "../common" }
nom = "7.1.3"
