[package]
name = "chess_alpha_beta"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess_core = { path = "../chess_core/" }
anyhow = "1.0.52"
