[package]
name = "chess_random"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = { path = "../../core", package= "chess_core"}
rand = "0.8.5"
